### ISSUE TITLE
User privileges & restrictions

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/pao#10]
tiap user tidak boleh dapat memasuki assessmen atau aktivitas yang bukan tanggung jawab mereka

**Comment by n1rw4n** [comment]
[https://app.zenhub.com/files/99688614/40796435-a6bc-43bc-8292-52f1709f2582/download](https://app.zenhub.com/files/99688614/40796435-a6bc-43bc-8292-52f1709f2582/download)

biar mempermudah role matrix
