### ISSUE TITLE
Activity statuses

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/pao#11]
open -> expired -> done ->  so_returned -> so_reviewed

**Comment by n1rw4n** [comment]
activity status bisa dilihat saat asessor melihat list user.

page akan berisi 
-- table header: nomer, nama, NIP, jabatan --> di klik, masuk ke hal 12 -17.
-- notifikasi : hijau done, merah belum disentuh, kuning mau kadaluarsa, jingga = reviewed by so
-- 7 hari dari Green status, sudah tidak bisa di edit lagi oleh asessor, so tetap bisa.

**Comment by renowijoyo** [comment]
ada tambahan status so_returned kalau hasil assessment dikembalikan ke assessor oleh second opinion
