### ISSUE TITLE
5 tipe project_role: admin, supervisor, assessor, assessee, secondopinion

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/pao#2]
Tipe ini di evaluasi saat dia masuk ke project_dashboard. dan ditunjukkan di page

![image](https://user-images.githubusercontent.com/2850146/29486002-62b5131a-8506-11e7-9fe2-b895b9207159.png)

menu project hanya akan muncul apabila modul project untuk profile itu active
contoh mengisi role suatu project ikuti gambar. attribute)1 adalah project_id

**Comment by n1rw4n** [comment]
supervisor = superadmin.

**Comment by n1rw4n** [comment]
tambah role : user

user akan dipakai orang kemenkes. untuk mantau perkembangan prosess asessment.

**Comment by n1rw4n** [comment]
user hanya bisa melihat summary data asessee. (see page 4 Mapping Data Assessment  Kemenkes.ppt). selain itu tidak ada akses lain.
