### ISSUE TITLE
butuh daftar notification, pesan, dan ditujukannya, dan kondisinya kapan notification tersebut diluncurkan

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/pao#25]

**Comment by nubogalalakon** [comment]
Notifikasi asesor:
1. Asesor sudah memiliki asessee dan dan data sudah masuk di sistem. **Notifikasi** : "Data asesee yang Anda ases sudah dapat diakses, silakan masukan user ID : .... dan password Anda : ...."
2. Saat draft laporan 1 sudah tersedia (hasil dari hari ke dua, lki - ljk dan uraian tersistem sudah tersedia), 
**Notifikasi**: "Draft laporan 1 yang terdiri dari psikogram, kompetensi gram, dan uraian kompetensi sudah tersedia, silakan ditindaklanjuti, untuk dibuat laporan final. Waktu Anda 7 hari setelah email ini diterima untuk melengkapi laporan."
3. Jika draft laporan belum ditreatment oleh asesor. **Notifikasi**: "Segera selesaikan laporan Anda, jika selesai Anda dapat mengikuti di batch selanjutnya." 
4. Jika laporan tidak sesuai dan sudah di SO hasilnya tidak  "OK" maka dikembalikan lagi ke asesor ybs dan dikasih feedback oleh SO-er, dan di beri warna merah di daftar Asesornya

**Comment by renowijoyo** [comment]
untuk yg no.1 ini notifikasinya by email ya kang?

**Comment by nubogalalakon** [comment]
No 1, by email betul mas
