### ISSUE TITLE
kesalahan pemberian rumpun pada laporan yang sudah dikumpulkan

### ISSUE THREAD

**Issue by bhirmbani** [gamantha/pao#46]
## What
bug

## Where
http://projects.ppsdm.com/index.php/projects/activity/view?id=284
atas nama Agus Hendroyono

## Solusi yang diinginkan
seharusnya beliau diberi rumpun Pusat eselon 3, bukannya biro_sekjen eselon3
intinya sih ingin diubah, cuman mungkin jangan sampai hilang uraian dan penilaian yang sudah diinput

## Masalah awal yang sudah diketahui
masalahnya sebenarnya di awal ketika penginputan data.
seharusnya pusat, namun saya menginputnya biro

**Comment by bhirmbani** [comment]
@qhyabdoel @renowijoyo @n1rw4n halo, ada yang tau database mana yang memungkinkan kita mengubah rumpun menjadi Pusat eselon 3 tanpa menimbulkan masalah ?

**Comment by qhyabdoel** [comment]
Kalo diubah catalog_id nya error

**Comment by qhyabdoel** [comment]
Pa @renowijoyo kalo ubah catalog_id di tabel project_assessment error
![image](https://user-images.githubusercontent.com/5150052/32710591-241b981e-c86c-11e7-858f-cbcaf05fcfcb.png)

Kayanya karena catalog_meta nya ga sesuai

**Comment by renowijoyo** [comment]
ini problemnya karena beda rumpun berarti beda aspek2 didalamnya. catalog_id yg baru akan minta aspek A, B, C, D misalkan. namun hasil dari rumpun yg salah adanya A, C, D, E. jadi akan ada error karena sistem akan minta A,B,C,D untuk ditampilkan namun di result hanya menyimpan A, C, D, E. jadi nanti aspek yg tidak ada seperti B harus ditambahkan manual, dan aspek yg tidak dipakai seperti E bisa dibiarkan saja. uraiannya tidak ada yg hilang. namun akan butuh LKI baru dan uraian baru

**Comment by qhyabdoel** [comment]
@renowijoyo aspeknya ditambah secara hardcode pa?

**Comment by renowijoyo** [comment]
1. rubah rumpun di profile meta
2. rubah catalog_id di table project_assessment (kalau no.2 & 1 tidak matching maka error juga)
3. tambahkan manual aspek yg belum ada di project_assessment_result. aspek2 ini sebenernya ditmabahkan otomatis saat init record kalau di project_assessment_result kosong. tpai karena sudah ada isinya maka tidak akan di init lagi

**Comment by qhyabdoel** [comment]
@renowijoyo ok
