### ISSUE TITLE
pengubahan LKJ untuk rumpun SESDIJEN

### ISSUE THREAD

**Issue by bhirmbani** [gamantha/pao#51]
## What
bug

## Where
LKJ di rumpun sesdijen

## How (Bagaimana bug ini muncul)
LKJ di rumpun sesdijen saat ini belum tepat

## Langkah yang sudah dilakukan
mengubah LKJ

## Solusi yang diinginkan

| KOMPETENSI        | LEVEL KOMPETENSI          |
| ------------- |-------------| 
| Kompetensi generik   |
| Integritas      | 4 
| Berorientasi Pada Pelayanan | 4 
| Kerjasama untuk sinergi | 4
| Profesionalitas | 3
| Kompetensi Spesifik |
| Perencanaan dan Pengorganisasian | 4
| Berpikir Strategis | 4
| Berpikir Analitis | 3
| Kepemimpinan Transformatif | 4
| Berorientasi Pada Kualitas| 3
| Komitmen Terhadap Organisasi | 3

## Screenshot
tidak ada

**Comment by qhyabdoel** [comment]
Udah beres @bhirmbani
