### ISSUE TITLE
Error saat klik print

### ISSUE THREAD

**Issue by bhirmbani** [gamantha/pao#52]
## What
bug

## Where
http://projects.ppsdm.com/index.php/projects/project_4/activity/print?id=1184

## How (Bagaimana bug ini muncul)
waktu klik print muncul error

## Solusi yang diinginkan
print berhasil

**Comment by n1rw4n** [comment]
Ini karena di project_acrtivity_meta dengan key = scheduled isinya tidak valid atau kosong

**Comment by n1rw4n** [comment]
![image](https://user-images.githubusercontent.com/23526539/32782001-9164eba6-c979-11e7-99c9-0d27415e30a8.png)
karena value nya seperti ini, default value harusnya [dd/mm/yyyy hh:mm:ss]
