### ISSUE TITLE
Error saat masuk ke proyek kemenkes

### ISSUE THREAD

**Issue by bhirmbani** [gamantha/pao#55]
## What
bug
akun ibu Rully tidak bisa masuk ke proyek kemenkes (proyek dengan projectid 1)

## Where
http://projects.ppsdm.com/index.php/projects/project/select
saat akun ibu Rully mencoba masuk ke proyek kemenkes muncul error

## How (Bagaimana bug ini muncul)
1. katanya awalnya dari pas sedang mengedit laporan di http://projects.ppsdm.com/index.php/projects/activity/view?id=922
2. setelah itu jadi tidak bisa masuk ke dashboard project id1
3. tapi kalo masuk dengan url nya langsung (http://projects.ppsdm.com/index.php/projects/activity/view?id=922), bisa masuk
4. jadi intinya gk bisa buka dashboardnya kemenkes saja sepertinya

### Rekap:
1. wktu pilih proyek kemenkes di halaman http://projects.ppsdm.com/index.php/projects/project/select muncul errornya
2. awalnya beliau mengerjakan normal seperti biasa, namun tiba2 jadi tidak bisa masuk

## Langkah yang sudah dilakukan
belum ada

## Yang sudah diketahui untuk menghilangkan bug
belum ada

## Solusi yang diinginkan
bisa masuk ke halaman dashboard projectid 1 (kemenkes)

## Screenshot
![error ruly](https://user-images.githubusercontent.com/12825389/32764642-36482516-c939-11e7-94f5-5eff275103b7.png)
![whatsapp image 2017-11-14 at 11 02 43 am](https://user-images.githubusercontent.com/12825389/32764644-3b67ebe4-c939-11e7-9a88-c916ac801a79.jpeg)

**Comment by renowijoyo** [comment]
error ini karena anyak profile yg tidak punya lastname. saat diminta ya kontan error. anehnya koq bisa sampai selama ini baru ketauan aja sih. ini SUDAH SOLVED

**Comment by bhirmbani** [comment]
oh oke begitu ya pak, ok saya inform ke dicky, apa baiknya di database dtambah sehingga ibu Rully bisa punya lastname ?
